
title: Christopher Norris
email: chris@cr-norris
description: Generalizing in communications, specializing in design and working with curious people to build organizations and tools with a holistic approach. On a perpetual mission to explore the outer limits of Alderworld, and currently unfolding a design language with Mosaic. Based in San Francisco and Vermont.
image: "../assets/images/crn-photo.jpg"
baseurl: "/"
url: "cr-norris.com"

permalink: /:title/

collections:
  pages:
    output: true
    permalink: /:title/

arena: "https://www.are.na/christopher-norris-1507041170/index"
instagram: "https://instagram.com/christophernorris"
spotify: "https://open.spotify.com/user/8tmepi9ym380wh7st5kac5ug7?si=296qFEiDQXyGUQV16sjgcQ"    