
title: Christopher Norris
email: chris@cr-norris
description: Enthusiastically generalising in all things design in Burlington, Vermont. On a perpetual mission to explore the outer limits of Alderworld with a team of close friends and collaborators. Currently unfolding a design language with Mosaic.
baseurl: "/"
url: "cr-norris.com"
permalink: /:title/

collections:
  pages:
    output: true
    permalink: /:title/